MLS/API/WebApp/Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ProductTypeController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.username = HttpContext.Session.GetString("Username");
            var accessToken = HttpContext.Session.GetString("JWTToken");
            using (var item = new HttpClient())
            {
                var endpoint = new Uri("https://localhost:44302/api/ProductType/GetAllProductTypes");
                item.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                var rs = item.GetAsync(endpoint).Result;
                var json = rs.Content.ReadAsStringAsync().Result;

                List<ProductType> prodlist = JsonConvert.DeserializeObject<List<ProductType>>(json);
                ViewBag.data = prodlist;
            }
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProductType productType)
        {
            var accessToken = HttpContext.Session.GetString("JWTToken");
            List<ProductType> prodlist = new List<ProductType>();            
            using (var item = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(productType), Encoding.UTF8, "application/json");
                var endpoint = new Uri("https://localhost:44302/api/ProductType/AddProductType");
                item.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                var rs = item.PostAsync(endpoint, content).Result;

                return RedirectToAction(nameof(Index));
            }
            return View();

        }

        public IActionResult Create()
        {      
            return View();
        }
        public IActionResult Edit( string id)
        {       
            ViewBag.username = HttpContext.Session.GetString("Username");          
            using (var item = new HttpClient())
            {
                var endpoint = new Uri("https://localhost:44302/api/ProductType/GetProductTypeById?id=" + id);
                var rs = item.GetAsync(endpoint).Result;
                var json = rs.Content.ReadAsStringAsync().Result;

                ProductType producttype = JsonConvert.DeserializeObject<ProductType>(json);
                ViewBag.producttype = producttype;
            }
            return View();
        }

        [HttpPost]
        public IActionResult Edit([Bind("Id,Name")] ProductType productType)
        {
           
            var accessToken = HttpContext.Session.GetString("JWTToken");          
            using (var item = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(productType), Encoding.UTF8, "application/json");
                var endpoint = new Uri("https://localhost:44302/api/ProductType/UpdateProductType?Id=" + productType.Id);
                item.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                var rs = item.PutAsync(endpoint, content).Result;
                var json = rs.Content.ReadAsStringAsync().Result;
            }

            return RedirectToAction("Index");
        }

    }
}

MLS/API/WebApp/Views/ProductType/Create.cshtml
@model WebApp.Models.ProductType

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ProductType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>          
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

MLS/API/WebApp/Views/ProductType/Edit.cshtml
@model WebApp.Models.ProductType

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Loại sản phẩm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>            
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" value="@ViewBag.producttype.Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

    @* script của upload *@

    <script>
        imgInp.onchange = evt => {
            const [file] = imgInp.files
            if (file) {
                blah.src = URL.createObjectURL(file)
            }
        }
    </script>

MLS/API/WebApp/Views/ProductType/Index.cshtml
@{
    ViewData["Title"] = "Administrator";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Dashboard</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>

        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Tất cả loại sản phẩm
            </div>
            <a asp-action="Create" asp-controller="ProductType" type="button" class="btn btn-outline-success"> Thêm</a>          
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Tên</th>
                            <th>Trạng thái</th>
                            <th> Options</th>
                        </tr>

                    </thead>
                    <tfoot>
                        <tr>
                            <th>Tên</th>
                            <th>Trạng thái</th>
                            <th>Options</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in ViewBag.data)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.Status</td>                             
                                <td>
                                    <a asp-action="Edit" asp-route-id = "@item.Id" type="button" class="btn btn-outline-success"> Sửa</a>
                                    <a asp-action="Edit" asp-route-id="@item.Id" type="button" class="btn btn-outline-danger"> Xóa</a>
                                   
                                </td>
                            </tr>

                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>