MLS/API/WebApp/Models/TradeMark.cs
using DAL.Entities.Product;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class TradeMark
    {
        public Guid Id { get; set; }
        public string  Name { get; set; }
        public  ProductType ProductType { get; set; }     
      
    }
}

MLS/API/WebApp/Controllers/TradeMarkController.cs
using DAL.Entities.Product;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;
using WebApp.Models;
using ProductType = WebApp.Models.ProductType;

namespace WebApp.Controllers
{
    public class TradeMarkController : Controller
    {


        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.username = HttpContext.Session.GetString("Username");
            var accessToken = HttpContext.Session.GetString("JWTToken");
            using (var item = new HttpClient())
            {
                var endpoint = new Uri("https://localhost:44302/api/TradeMark/GetAllTradeMarks");
                item.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                var rs = item.GetAsync(endpoint).Result;
                var json = rs.Content.ReadAsStringAsync().Result;

                List<TradeMark> trademarklist = JsonConvert.DeserializeObject<List<TradeMark>>(json);
                ViewBag.data = trademarklist;
            }
            return View();
        }
        [HttpPost]
        public IActionResult Create(TradeMark tradeMark)
        {
            var accessToken = HttpContext.Session.GetString("JWTToken");
            List<TradeMark> prodlist = new List<TradeMark>();
            using (var item = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(tradeMark), Encoding.UTF8, "application/json");
                var endpoint = new Uri("https://localhost:44302/api/TradeMark/AddTradeMark");
                item.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                var rs = item.PostAsync(endpoint, content).Result;

                return RedirectToAction(nameof(Index));
            }
            return View();

        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Edit(string id)
        {
            using (var item = new HttpClient())
            {
                ViewBag.username = HttpContext.Session.GetString("Username");

                TradeMark tradeMark = new TradeMark();

                var endpoint = new Uri("https://localhost:44302/api/ProductType/GetProductTypeById?id=" + tradeMark.Id);
                var rs = item.GetAsync(endpoint).Result;
                var json = rs.Content.ReadAsStringAsync().Result;

                ProductType producttype = JsonConvert.DeserializeObject<ProductType>(json);
                ViewBag.producttype = producttype;
            }
          
            using (var item = new HttpClient())
            {
                var endpoint = new Uri("https://localhost:44302/api/TradeMark/GetTradeMarkByProductTypeId?id=" + id);
                var rs = item.GetAsync(endpoint).Result;
                var json = rs.Content.ReadAsStringAsync().Result;
                TradeMark tradeMark = JsonConvert.DeserializeObject<TradeMark>(json);
                ViewBag.producttype = tradeMark;
            }
            return View();
        }

        [HttpPost]
        public IActionResult Edit([Bind("Id,Name")] TradeMark tradeMark)
        {

            var accessToken = HttpContext.Session.GetString("JWTToken");
            using (var item = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(tradeMark), Encoding.UTF8, "application/json");
                var endpoint = new Uri("https://localhost:44302/api/TradeMark/UpdateTradeMark?Id=" + tradeMark.Id);
                item.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                var rs = item.PutAsync(endpoint, content).Result;
                var json = rs.Content.ReadAsStringAsync().Result;
            }

            return RedirectToAction("Index");

        }
    }
}

MLS/API/WebApp/Views/TradeMark/Create.cshtml
@model WebApp.Models.TradeMark

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ProductType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

MLS/API/WebApp/Views/TradeMark/Edit.cshtml
@model WebApp.Models.TradeMark

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Nhãn hàng</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductType" class="control-label">Loại sản phẩm</label>
                <select class="form-select" asp-for="ProductType" aria-label="Default select example">
                    @foreach (var item in ViewBag.data)
                    {
                        <option value=@item.Id>@item.Name</option>

                    }
                    <option selected="selected" disabled value=@ViewBag.product.ProductTypeId>@ViewBag.producttype.Name</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" value="@ViewBag.tradeMark.Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

MLS/API/WebApp/Views/TradeMark/Index.cshtml
@{
    ViewData["Title"] = "Administrator";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Dashboard</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>

        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Tất cả nhãn hàng
            </div>
            <a asp-action="Create" asp-controller="TradeMark" type="button" class="btn btn-outline-success"> Thêm</a>
            <div class="container-fluid px-4">
              
           </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Tên</th>
                            <th>Options</th>
                        </tr>

                    </thead>
                    <tfoot>
                        <tr>
                            <th>Tên</th> 
                            <th>Options</th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in ViewBag.data)
                        {
                            <tr>
                                <td>@item.Name</td>                            
                                <td>
                                    <a asp-action="Edit" asp-route-id="@item.Id" type="button" class="btn btn-outline-success"> Sửa</a>
                                    <a asp-action="Edit" asp-route-id="@item.Id" type="button" class="btn btn-outline-danger"> Xóa</a>
                                </td>
                            </tr>

                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>